### ISSUE TITLE
Unable to find Sunmi keys 

### ISSUE THREAD

**Issue by MohammedAlmeshal** [sunmi-OS/sunmi-openapi-java-sdk#3]
Could you please let me know where I can find the following credentials? 
I'm unable to find them in the app page in sunmi partner

- appId
- appKey
- appPrivateKey
- sunmiPublicKey

**Comment by luduoxin** [comment]
![image](https://user-images.githubusercontent.com/3434402/172781455-842161cd-7258-40be-b464-5bf5405db09a.png)
